config/routes.rb
Rails.application.routes.draw do
  
  
  get 'export/index'
  get 'export/day'
  get 'export/week'
  post 'export/export_day'
  post 'export/export_week'
  resources :professionals do
    resources :appointments do
      collection do
        delete 'destroy_all', action: "destroy_all", as: 'destroy_all'
      end
    end
  end
  root to: 'home#show'
  get 'home/show'
  
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :users
end

app/models/professional.rb
class Professional < ApplicationRecord
    has_many :appointments

    validates :name, presence: { message: "El profesional debe tener un nombre" }, uniqueness: { message: "El nombre ingresado ya está registrado en el sistema" }, length: { in: 1..50, message: "El nombre debe tener entre 1 y 50 caracteres"}

    before_destroy do | professional |
        if professional.appointments.futures.count > 0
            professional.errors.add( :base, "El profesional seleccionado tiene turnos a futuro, por lo que no puede eliminarse")
            throw :abort
        else
            professional.appointments.destroy_all
        end
    end
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  before_action :set_professional, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /professionals or /professionals.json
  def index
    has_permission('professional_index')
    @professionals = Professional.all
  end

  # GET /professionals/1 or /professionals/1.json
  def show
    has_permission('professional_show')
  end

  # GET /professionals/new
  def new
    has_permission('professional_new')
    @professional = Professional.new
  end

  # GET /professionals/1/edit
  def edit
    has_permission('professional_update')
  end

  # POST /professionals or /professionals.json
  def create
    has_permission('professional_new')
    @professional = Professional.new(professional_params)

    respond_to do |format|
      if @professional.save
        format.html { redirect_to @professional, notice: "Profesional creado con éxito." }
        format.json { render :show, status: :created, location: @professional }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professionals/1 or /professionals/1.json
  def update
    has_permission('professional_update')
    respond_to do |format|
      if @professional.update(professional_params)
        format.html { redirect_to @professional, notice: "Profesional actualizado con éxito." }
        format.json { render :show, status: :ok, location: @professional }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @professional.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professionals/1 or /professionals/1.json
  def destroy
    if has_permission('professional_destroy')
      respond_to do |format|
        if @professional.destroy
          format.html { redirect_to professionals_url, notice: "Profesional eliminado con éxito." }
          format.json { head :no_content }
        else
          format.html { redirect_to professionals_url, alert: "El profesional seleccionado tiene turnos a futuro, por lo que no puede eliminarse" }
          format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professional
      @professional = Professional.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def professional_params
      params.require(:professional).permit(:name)
    end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper

    def professionals_names
        arr1 = ["-"]
        arr2 = Professional.all.map { |each| each.name }
        arr1.concat arr2
    end
end

app/views/professionals/_form.html.erb
<%= form_with(model: professional) do |form| %>
  <% if professional.errors.any? %>
    <div id="error_explanation">
      <% professional.errors.each do |error| %>
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <%= error.full_message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <p><%= form.label :name, "Nombre:" %><br>
    <%= form.text_field :name %></p>
  </div>

  <div class="actions">
    <p><%= form.submit "Guardar"%></p>
  </div>
<% end %>

app/views/professionals/edit.html.erb
<h1>Editar Profesional</h1>

<%= render 'form', professional: @professional %>

<% if has_permission('professional_show')%>
<%= link_to 'Ver', @professional %> | 
<% end%>
<%= link_to 'Volver', professionals_path %>

app/views/professionals/index.html.erb
<h1>Profesionales</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professionals.each do |professional| %>
      <tr>
        <td><%= professional.name %></td>
        <% if has_permission('professional_show')%>
        <td><%= link_to 'Ver', professional %></td>
        <% end %>

        <% if has_permission('appointment_index')%>
        <td> | <%= link_to 'Turnos', professional_appointments_path(professional) %></td>
        <% end %>

        <% if has_permission('professional_update')%>
        <td> | <%= link_to 'Editar', edit_professional_path(professional) %></td>
        <% end %>

        <% if has_permission('professional_destroy')%>
        <td> | <%= link_to 'Eliminar', professional, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if has_permission('professional_new')%>
<%= link_to 'Crear nuevo Profesional', new_professional_path %>
<% end %>

app/views/professionals/new.html.erb
<h1>Nuevo Profesional</h1>

<%= render 'form', professional: @professional %>

<%= link_to 'Volver', professionals_path %>

app/views/professionals/show.html.erb
<h1>Profesional</h1>
<p>
  <strong>Nombre:</strong>
  <%= @professional.name %>
</p>

<% if has_permission('professional_update')%>
<%= link_to 'Editar', edit_professional_path(@professional) %>
 | 
 <% end %>
<%= link_to 'Volver', professionals_path %>