config/routes.rb
Rails.application.routes.draw do
  
  
  get 'export/index'
  get 'export/day'
  get 'export/week'
  post 'export/export_day'
  post 'export/export_week'
  resources :professionals do
    resources :appointments do
      collection do
        delete 'destroy_all', action: "destroy_all", as: 'destroy_all'
      end
    end
  end
  root to: 'home#show'
  get 'home/show'
  
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :users
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :professional

  validates :first_name, presence: { message: "Debe ingresarse el nombre del paciente" }, length: { in: 1..50, message: "El nombre del paciente debe tener entre 1 y 50 caracteres"}
  validates :last_name, presence: { message: "Debe ingresarse el apellido del paciente" }, length: { in: 1..50, message: "El apellido del paciente debe tener entre 1 y 50 caracteres"}
  validates :phone, presence: { message: "Debe ingresarse el teléfono del paciente" }, length: { in: 1..50, message: "El teléfono del paciente debe tener entre 1 y 30 caracteres"}
  #validates :professional, presence: { message: "Debe indicarse a que profesional corresponde el turno"}
  validates :date, presence: { message: "Debe ingresarse una fecha y hora para el turno" }
  validate :futute_date
  validates :date, uniqueness: { scope: :professional, message: "El profesional no está disponible en la fecha y hora indicada"}


  def futute_date
    if date && date.past?
      errors.add(:base, "La fecha y hora del turno debe ser en el futuro")
    end
  end

  scope :futures, -> { where("date > ?", DateTime.now) }
  scope :in_day, -> (start_date) { where date: start_date.all_day}
  scope :in_week, -> (start_date) { where date: start_date.all_week}
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_professional
  before_action :set_appointment, only: %i[ show edit update destroy ]

  # GET /appointments or /appointments.json
  def index
    has_permission('appointment_index')
    @appointments = @professional.appointments.all
  end

  # GET /appointments/1 or /appointments/1.json
  def show
    has_permission('appointment_show')
  end

  # GET /appointments/new
  def new
    has_permission('appointment_new')
    @appointment = @professional.appointments.new
  end

  # GET /appointments/1/edit
  def edit
    if has_permission('appointment_update')
      if @appointment.date.past?
        flash[:alert] = "No se puede modificar un turno pasado"
        redirect_to professional_appointments_url(@professional)
      end
    end
  end

  # POST /appointments or /appointments.json
  def create
    has_permission('appointment_new')
    @appointment = @professional.appointments.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to professional_appointment_path(@professional, @appointment), notice: "Turno creado con éxito." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1 or /appointments/1.json
  def update
    has_permission('appointment_update')
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to professional_appointment_path(@professional, @appointment), notice: "Turno actualizado con éxito." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1 or /appointments/1.json
  def destroy
    if has_permission('appointment_destroy')
      respond_to do |format|
        if @appointment.date.future?
          @appointment.destroy
          format.html { redirect_to professional_appointments_url(@professional), notice: "Turno cancelado con éxito." }
          format.json { head :no_content }
        else
          format.html { redirect_to professional_appointments_url(@professional), alert: "No se puede cancelar un turno pasado." }
          format.json { head :no_content }
        end
      end
    end
  end

  def destroy_all
    if has_permission('appointment_destroy')
      @professional.appointments.futures.destroy_all
      flash[:notice] = "Todos los turnos futuros de #{@professional.name} fueron cancelados"
      redirect_to professional_appointments_url(@professional)
    end
  end

  private

    def set_professional
      @professional = Professional.find(params[:professional_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = @professional.appointments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:date, :first_name, :last_name, :phone, :notes)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: [professional, appointment]) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <% appointment.errors.each do |error| %>
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <%= error.full_message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
      <% end %>
    </div>
  <% end %>

  <div class="field">
    <p><%= form.label :date, "Fecha y hora:" %><br>
    <%= form.datetime_select :date %></p>
  </div>

  <div class="field">
    <p><%= form.label :first_name, "Nombre/s:" %><br>
    <%= form.text_field :first_name %></p>
  </div>

  <div class="field">
    <p><%= form.label :last_name, "Apellido/s:" %><br>
    <%= form.text_field :last_name %></p>
  </div>

  <div class="field">
    <p><%= form.label :phone, "Teléfono:" %><br>
    <%= form.text_field :phone %></p>
  </div>

  <div class="field">
    <p><%= form.label :notes, "Notas adicionales:" %><br>
    <%= form.text_area :notes %></p>
  </div>

  <div class="actions">
    <p><%= form.submit "Guardar" %></p>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editar turno</h1>

<%= render 'form', appointment: @appointment, professional: @professional %>

<% if has_permission('appointment_show')%>
<%= link_to 'Ver', [@professional, @appointment] %> | 
<% end %>
<%= link_to 'Volver', professional_appointments_path(@professional) %>

app/views/appointments/index.html.erb
<h1>Turnos de <%= @professional.name %></h1>

<p>
<% if has_permission('appointment_destroy')%>
  <%= link_to 'Cancelar todos los turnos', destroy_all_professional_appointments_path(@professional), method: :delete, data: { confirm: 'Estas seguro?' } %>
<% end %>
</p>

<table>
  <thead>
    <tr>
      <th>Fecha y hora</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Teléfono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date.strftime("%Y/%m/%d %H:%M") %></td>
        <td><%= appointment.first_name %></td>
        <td><%= appointment.last_name %></td>
        <td><%= appointment.phone %></td>
        <% if has_permission('appointment_show')%>
        <td><%= link_to 'Ver', [@professional, appointment] %></td>
        <% end %>

        <% if has_permission('appointment_update')%>
        <td> | <%= link_to 'Editar', edit_professional_appointment_path(@professional, appointment) %></td>
        <% end %>

        <% if has_permission('appointment_destroy') && appointment.date.future?%>
        <td> | <%= link_to 'Cancelar', [@professional, appointment], method: :delete, data: { confirm: 'Estas seguro?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>
<% if has_permission('appointment_new')%>
<%= link_to 'Crear nuevo turno', new_professional_appointment_path(@professional) %>
<% end %>
</p>

app/views/appointments/new.html.erb
<h1>Nuevo turno</h1>

<%= render 'form', appointment: @appointment, professional: @professional %>

<p>
<%= link_to 'Volver', professional_appointments_path(@professional) %>
</p>

app/views/appointments/show.html.erb
<h1>Turno de <%= @professional.name %></h1>

<p>
  <strong>Fecha y hora:</strong>
  <%= @appointment.date.strftime("%Y/%m/%d %H:%M") %>
</p>

<p>
  <strong>Nombre del paciente:</strong>
  <%= @appointment.first_name %>
</p>

<p>
  <strong>Apellido del paciente:</strong>
  <%= @appointment.last_name %>
</p>

<p>
  <strong>Teléfono:</strong>
  <%= @appointment.phone %>
</p>

<p>
  <strong>Notas adicionales:</strong>
  <%= @appointment.notes %>
</p>

<p>
<% if has_permission('appointment_update')%>
<%= link_to 'Editar', edit_professional_appointment_path(@professional, @appointment) %> | 
<% end %>
<%= link_to 'Volver', professional_appointments_path(@professional) %>
</p>